# Generated by Django 2.0.7 on 2018-07-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoNinjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='add description at later time'),
            preserve_default=False,
        ),
    ]
