# Generated by Django 2.0.7 on 2018-07-20 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likesBooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectee', to='likesBooks.Buser')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='liked_users',
        ),
        migrations.RemoveField(
            model_name='book',
            name='uploader',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='user',
            name='likers',
            field=models.ManyToManyField(related_name='_user_likers_+', to='likesBooks.User'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='connection',
            name='connectee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector', to='likesBooks.Person'),
        ),
        migrations.AddField(
            model_name='connection',
            name='connector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectee', to='likesBooks.Person'),
        ),
    ]
